services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env.dev
    ports:
      - "8000:8000"

  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env.dev
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
